### Loading datasets, and learning about the data

In [66]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
import mglearn

In [ ]:
#!pip install mglearn


   ---------------------------------------- 0.0/581.4 kB ? eta -:--:--
    --------------------------------------- 10.2/581.4 kB ? eta -:--:--
   - ------------------------------------- 20.5/581.4 kB 330.3 kB/s eta 0:00:02
   - ------------------------------------- 20.5/581.4 kB 330.3 kB/s eta 0:00:02
   - ------------------------------------- 20.5/581.4 kB 330.3 kB/s eta 0:00:02
   - ------------------------------------- 20.5/581.4 kB 330.3 kB/s eta 0:00:02
   ----- --------------------------------- 81.9/581.4 kB 306.3 kB/s eta 0:00:02
   ----- --------------------------------- 81.9/581.4 kB 306.3 kB/s eta 0:00:02
   ----- --------------------------------- 81.9/581.4 kB 306.3 kB/s eta 0:00:02
   -------- ----------------------------- 122.9/581.4 kB 300.4 kB/s eta 0:00:02
   -------- ----------------------------- 133.1/581.4 kB 302.7 kB/s eta 0:00:02
   ---------- --------------------------- 163.8/581.4 kB 328.2 kB/s eta 0:00:02
   ------------ ------------------------- 184.3/581.4 kB 


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\Betina Kuriakose\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:

iris_dataset= load_iris()
print("Keys of the dataset:{}".format(iris_dataset.keys()))

In [32]:
print(iris_dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [33]:
print("target names:{}".format(iris_dataset.target_names))
print("feature names:{}".format(iris_dataset.feature_names))

target names:['setosa' 'versicolor' 'virginica']
feature names:['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [34]:
print("data:{}",format(iris_dataset.data))

data:{} [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

In [35]:
print("shapr of the data:{}".format(iris_dataset.data.shape))

shapr of the data:(150, 4)


In [36]:
print("type of the target:{}".format(type(iris_dataset.target)))

type of the target:<class 'numpy.ndarray'>


In [37]:
print("target:{}",format(iris_dataset.target))

target:{} [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [38]:
print("target shape:{}".format(iris_dataset.target.shape))

target shape:(150,)


### Plotting the data to visualize the data

In [61]:
iris_dataframe=pd.DataFrame(data=X_train,columns=iris_dataset.feature_names)
print(iris_dataframe.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.0               3.6                1.4               0.2
1                5.2               4.1                1.5               0.1
2                5.8               2.7                5.1               1.9
3                6.0               3.4                4.5               1.6
4                6.7               3.1                4.7               1.5


In [1]:
pd.plotting.scatter_matrix(iris_dataframe,c=y_train,figsize=(15,15),marker='o',hist_kwds={'bins':20},s=60,alpha=.8,cmap=mglearn.cm3)

NameError: name 'pd' is not defined

### Training and testing data

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(iris_dataset.data, iris_dataset.target, test_size=0.25, random_state=42)

In [41]:
print("Xtrain shape",X_train.shape)

Xtrain shape (112, 4)


In [42]:
print("y_train",y_train)

y_train [0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1 2 0 1 2 0 2 2 1
 1 2 1 0 1 2 0 0 1 1 0 2 0 0 1 1 2 1 2 2 1 0 0 2 2 0 0 0 1 2 0 2 2 0 1 1 2
 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1
 2]


In [43]:
print(y_train.shape)

(112,)


In [44]:
print("X_test shape:{}".format(X_test.shape))
print("y_test shape:{}".format(y_test.shape))

X_test shape:(38, 4)
y_test shape:(38,)


### Building a model using K nearest neighbors

In [45]:
from sklearn.neighbors import KNeighborsClassifier

In [46]:
knn= KNeighborsClassifier(n_neighbors=1)

In [47]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

### Predict the data

In [51]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape:{}".format(X_new.shape))

X_new.shape:(1, 4)


In [ ]:
prediction= knn.predict(X_new)
print("Prediction:{}".format(prediction))
print("Predicted target name:{}".format(iris_dataset.target_names[prediction]))

Prediction:[0]
Predicted target name:['setosa']


### Evaluate the model

In [54]:
y_pred= knn.predict(X_test)
print("Test set prediction:\n{}".format(y_pred))


Test set prediction:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [56]:
print("Test set score: {:.2f}".format(np.mean(y_pred==y_test)))

Test set score: 1.00


In [59]:
print("test set score: {}".format(knn.score(X_test,y_test)))

test set score: 1.0
